Feat
KumarAmitt/Enumerable-Methods pull request #1
Opened 2021-01-08 08:35 UTC by KumarAmitt

**Project - Enumerable Methods**

-- Implement custom enumerable methods

`my_each`
`my_each_with_index`
`my_select`
`my_all?`
`my_any?`
`my_none?`
`my_count`
`my_map`
`my_inject`
`multiply_els`

-- Any feedback and suggestion to improve this project will be highly appreciated.

2021-01-08 13:24 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Ralph Oburu & Amit Kumar** 
Good job with your first submission for this project :muscle:  :muscle:
It passes most of the tests :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] Fix ruboop offenses
- [ ] Add a screenshot in the README file
- [ ] #my_each_with_index when a block is given when self is an array
     ```
      concat1=''
      [1,2,3,4].each_with_index(&proc{|n, i| concat1+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat2=''
      [1,2,3,4].each_with_index(&proc{|n, i| concat2+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat1 == concat2
     ```
       behaves like #each_with_index calls the given block once for each element in self
- [ ] #my_each_with_index when a block is given when self is a range
     ```
      concat1=''
      (1..4).each_with_index(&proc{|n, i| concat1+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat2=''
      (1..4).each_with_index(&proc{|n, i| concat2+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat1 == concat2
     ```
       behaves like #each_with_index calls the given block once for each element in self
- [ ] #my_each_with_index when a block is given when self is a hash
     ```
      concat1=''
      { a: 1, b: 2, c: 3, d: 4}.each_with_index(&proc{|n, i| concat1+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat2=''
      { a: 1, b: 2, c: 3, d: 4}.each_with_index(&proc{|n, i| concat2+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat1 == concat2
    ```
       behaves like #each_with_index calls the given block once for each element in self
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-01-08 15:48 UTC, mcrd25 requested changes
# Changes Required

Hi Team :wave: 

Good job so far. There only 3 tests failing on my end.

### Required Changes
- Fix issues with `my_each_with_index`

***Please makes changes and submit another review request.
If you have any questions, let me know here or email (preferably) or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

If you liked my review, consider upskilling me on LinkedIn. And please do connect. [My LinkedIn](https://www.linkedin.com/in/mayadouglas/)

*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2021-01-08 15:48 UTC, mcrd25 commented on enumerable.rb
> +  def my_each_with_index
You technically give the right answer but you are giving the wrong output. It's an array

2021-01-08 15:48 UTC, mcrd25 commented on enumerable.rb
> +  def my_each_with_index
![Screenshot from 2021-01-08 11-47-04](https://user-images.githubusercontent.com/31193823/104034471-4b523880-51a7-11eb-9fdc-824ec7457892.png)

2021-01-08 15:48 UTC, mcrd25 commented on enumerable.rb
> +  def my_each_with_index
![Screenshot from 2021-01-08 11-47-47](https://user-images.githubusercontent.com/31193823/104034524-5dcc7200-51a7-11eb-8565-8df5aacae35e.png)

2021-01-08 21:04 UTC, ebeagusamuel requested changes
# Changes Required :recycle: 
### Hey guys
#### You are almost there. There are just two test cases failing. 
- [ ] enumerables #my_each when a block is given when self is a hash behaves like #each calls the given block once for each element in self.
- [ ] enumerables #my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self.
### Once these are fixed are done, then your project can be approved. Do request another review when you make the fixes.
slack(@ebeagusamuel)

2021-01-09 13:49 UTC, javitocor approved these changes
# STATUS APPROVED 🥇 

Congratulations team! 🥳 
You have made a great job with the enumerables 👍 
Remember to merge it, fill up the completion form 📑  and you can move into the next project 🚀 
Good luck with it! 😃

2021-01-09 13:53 UTC, merged